[package]
org = "pasidalee_dissanayak"
name = "gramaApp"
version = "0.1.0"
distribution = "2201.3.2"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"
